import "server-only";
import { notFound } from "next/navigation";
import { requireOfficeContext } from "@/lib/customers/data";
import { createClient } from "@/lib/supabase/server";
import { QUOTE_PAGE_SIZE } from "./query";
import type { Quote, QuoteActivity, QuoteStatus } from "./types";
import { isQuoteId } from "./validation";
const columns = "id,organization_id,customer_id,enquiry_id,quote_number,status,issue_date,expiry_date,currency,notes,terms,subtotal_cents,tax_cents,total_cents,sent_at,accepted_at,rejected_at,created_at,updated_at,customers(id,first_name,last_name,email,phone,address_line_1,address_line_2,suburb,city,postcode),enquiries(id,category,description,status)";
export async function listQuotes(p: { organizationId: string; page: number; query: string; status: QuoteStatus | "all" }) {
  const s = await createClient(); const from = (p.page - 1) * QUOTE_PAGE_SIZE; let customerIds: string[] = [];
  if (p.query) { const pattern = `%${p.query}%`; const r = await s.from("customers").select("id").eq("organization_id", p.organizationId).or(`first_name.ilike.${pattern},last_name.ilike.${pattern},email.ilike.${pattern}`).limit(100); customerIds = (r.data ?? []).map(x => x.id); }
  let request = s.from("quotes").select(columns, { count: "exact" }).eq("organization_id", p.organizationId).order("created_at", { ascending: false }).range(from, from + QUOTE_PAGE_SIZE - 1);
  if (p.status !== "all") request = request.eq("status", p.status); if (p.query) request = request.or(`quote_number.ilike.%${p.query}%${customerIds.length ? `,customer_id.in.(${customerIds.join(",")})` : ""}`);
  const r = await request; if (r.error) throw new Error("Unable to load quotes."); return { quotes: (r.data ?? []) as unknown as Quote[], count: r.count ?? 0 };
}
export async function getQuote(id: string, organizationId: string) { if (!isQuoteId(id)) notFound(); const s = await createClient(); const r = await s.from("quotes").select(`${columns},quote_items(id,description,quantity,unit_price_cents,tax_rate,line_subtotal_cents,tax_cents,line_total_cents,position)`).eq("organization_id", organizationId).eq("id", id).order("position", { referencedTable: "quote_items", ascending: true }).maybeSingle(); if (r.error || !r.data) notFound(); return r.data as unknown as Quote; }
export async function getQuoteActivity(id: string, organizationId: string) { const s = await createClient(); const r = await s.from("activity_logs").select("id,summary,created_at").eq("organization_id", organizationId).eq("entity_type", "quote").eq("entity_id", id).order("created_at", { ascending: false }).limit(20); if (r.error) throw new Error("Unable to load quote activity."); return (r.data ?? []) as QuoteActivity[]; }
export async function searchQuoteCustomers(organizationId: string, query = "", selectedId?: string) { const s = await createClient(); let q = s.from("customers").select("id,first_name,last_name,email,phone").eq("organization_id", organizationId).eq("status", "active").order("last_name").limit(20); if (query) q = q.or(`first_name.ilike.%${query}%,last_name.ilike.%${query}%,email.ilike.%${query}%,phone.ilike.%${query}%`); const [r, selected] = await Promise.all([q, selectedId && isQuoteId(selectedId) ? s.from("customers").select("id,first_name,last_name,email,phone").eq("organization_id", organizationId).eq("status", "active").eq("id", selectedId).maybeSingle() : Promise.resolve({ data: null, error: null })]); if (r.error || selected.error) throw new Error("Unable to load customers."); const customers = r.data ?? []; return selected.data && !customers.some(customer => customer.id === selected.data!.id) ? [selected.data, ...customers] : customers; }
export async function getQuoteEnquiries(organizationId: string, customerId?: string) { if (!customerId || !isQuoteId(customerId)) return []; const s = await createClient(); const r = await s.from("enquiries").select("id,customer_id,category,description,status").eq("organization_id", organizationId).eq("customer_id", customerId).neq("status", "closed").order("created_at", { ascending: false }).limit(30); if (r.error) throw new Error("Unable to load enquiries."); return r.data ?? []; }
export async function getQuoteDefaults(organizationId: string) { const s = await createClient(); const r = await s.rpc("get_quote_defaults", { p_organization_id: organizationId }); if (r.error || !r.data?.[0]) throw new Error("Unable to load quote settings."); return r.data[0] as { quote_validity_days: number; currency: string; default_gst_rate: number; gst_registered: boolean }; }
export async function getRecentCustomerQuotes(customerId: string, organizationId: string) { const s = await createClient(); const r = await s.from("quotes").select("id,quote_number,status,total_cents,currency,created_at").eq("organization_id", organizationId).eq("customer_id", customerId).order("created_at", { ascending: false }).limit(5); return r.error ? [] : r.data ?? []; }
export async function getEnquiryQuotes(enquiryId: string, organizationId: string) { const s = await createClient(); const r = await s.from("quotes").select("id,quote_number,status,total_cents,currency,created_at").eq("organization_id", organizationId).eq("enquiry_id", enquiryId).order("created_at", { ascending: false }).limit(5); return r.error ? [] : r.data ?? []; }
export const requireQuoteOfficeContext = requireOfficeContext;
