"use client";
import Link from "next/link";
import { Plus, Trash2 } from "lucide-react";
import { useActionState, useMemo, useState } from "react";
import { FieldError } from "@/components/auth/field-error";
import { calculateLine, formatMoney, parseMoneyToCents, parseQuantityMilli } from "@/lib/quotes/money";
import type { Quote, QuoteEnquiry } from "@/lib/quotes/types";
import { initialQuoteState, type QuoteActionState } from "@/lib/quotes/validation";
type Customer = { id: string; first_name: string; last_name: string; email: string | null; phone: string | null };
type Line = { key: number; description: string; quantity: string; unitPrice: string };
const emptyLine = (key: number): Line => ({ key, description: "", quantity: "1", unitPrice: "" });
export function QuoteForm({ action, customers, enquiries, quote, selectedCustomerId, selectedEnquiryId, expiryDate, taxRate = 15, currency = "NZD" }: { action: (s: QuoteActionState, f: FormData) => Promise<QuoteActionState>; customers: Customer[]; enquiries: QuoteEnquiry[]; quote?: Quote; selectedCustomerId?: string; selectedEnquiryId?: string; expiryDate: string; taxRate?: number; currency?: string }) {
  const [state, formAction, pending] = useActionState(action, initialQuoteState); const [nextKey, setNextKey] = useState((quote?.quote_items?.length ?? 0) + 1); const [lines, setLines] = useState<Line[]>(quote?.quote_items?.map((x, i) => ({ key: i, description: x.description, quantity: String(x.quantity), unitPrice: (x.unit_price_cents / 100).toFixed(2) })) ?? [emptyLine(0)]);
  const preview = useMemo(() => lines.map(line => { const q = parseQuantityMilli(line.quantity); const p = parseMoneyToCents(line.unitPrice); return q === null || p === null ? null : calculateLine(q, p, taxRate); }), [lines, taxRate]); const subtotal = preview.reduce((sum, x) => sum + (x?.subtotalCents ?? 0), 0); const tax = preview.reduce((sum, x) => sum + (x?.taxCents ?? 0), 0);
  const update = (key: number, field: keyof Omit<Line, "key">, value: string) => setLines(items => items.map(x => x.key === key ? { ...x, [field]: value } : x));
  return <form action={formAction} className="customer-form quote-form">
    <section className="form-section"><div className="form-section-heading"><p className="eyebrow">Customer</p><h2>Quote relationship</h2><p>Only active customers and their open enquiries can be linked.</p></div><div className="form-section-fields"><div className="field-group"><label htmlFor="customerId">Customer</label><select defaultValue={quote?.customer_id ?? selectedCustomerId ?? ""} id="customerId" name="customerId" required><option value="">Select customer</option>{customers.map(c => <option key={c.id} value={c.id}>{c.first_name} {c.last_name}{c.email ? ` · ${c.email}` : ""}</option>)}</select><FieldError errors={state.fieldErrors?.customerId} id="customerId-error" /></div><div className="field-group"><label htmlFor="enquiryId">Related enquiry (optional)</label><select defaultValue={quote?.enquiry_id ?? selectedEnquiryId ?? ""} id="enquiryId" name="enquiryId"><option value="">No enquiry</option>{enquiries.map(e => <option key={e.id} value={e.id}>{e.category || e.description.slice(0, 70)}</option>)}</select><FieldError errors={state.fieldErrors?.enquiryId} id="enquiryId-error" /></div><div className="field-group"><label htmlFor="expiryDate">Valid until</label><input defaultValue={quote?.expiry_date ?? expiryDate} id="expiryDate" name="expiryDate" required type="date" /><FieldError errors={state.fieldErrors?.expiryDate} id="expiryDate-error" /></div></div></section>
    <section className="quote-editor"><div className="quote-editor-heading"><div><p className="eyebrow">Pricing</p><h2>Line items</h2></div><button className="button button-secondary" onClick={() => { setLines(x => [...x, emptyLine(nextKey)]); setNextKey(x => x + 1); }} type="button"><Plus size={15} />Add line</button></div><div className="quote-lines">{lines.map((line, index) => <div className="quote-line" key={line.key}><div className="field-group quote-description"><label htmlFor={`description-${line.key}`}>Description</label><input id={`description-${line.key}`} maxLength={500} name="description" onChange={e => update(line.key, "description", e.target.value)} required value={line.description} /></div><div className="field-group"><label htmlFor={`quantity-${line.key}`}>Quantity</label><input id={`quantity-${line.key}`} inputMode="decimal" name="quantity" onChange={e => update(line.key, "quantity", e.target.value)} required value={line.quantity} /></div><div className="field-group"><label htmlFor={`price-${line.key}`}>Unit price</label><div className="money-input"><span>$</span><input id={`price-${line.key}`} inputMode="decimal" name="unitPrice" onChange={e => update(line.key, "unitPrice", e.target.value)} placeholder="0.00" required value={line.unitPrice} /></div></div><div className="quote-line-total"><span>Line total</span><strong>{preview[index] ? formatMoney(preview[index]!.totalCents, currency) : "—"}</strong></div><button aria-label={`Remove line ${index + 1}`} className="icon-button quote-remove" disabled={lines.length === 1} onClick={() => setLines(x => x.filter(item => item.key !== line.key))} type="button"><Trash2 size={16} /></button></div>)}</div><FieldError errors={state.fieldErrors?.items} id="items-error" /><dl className="quote-totals"><div><dt>Subtotal</dt><dd>{formatMoney(subtotal, currency)}</dd></div><div><dt>GST {taxRate}%</dt><dd>{formatMoney(tax, currency)}</dd></div><div><dt>Total</dt><dd>{formatMoney(subtotal + tax, currency)}</dd></div></dl><p className="quote-preview-note">Preview only. KiwiOps calculates and stores final totals in the database.</p></section>
    <section className="form-section"><div className="form-section-heading"><p className="eyebrow">Document</p><h2>Notes and terms</h2><p>These fields become locked when the quote is issued.</p></div><div className="form-section-fields"><div className="field-group"><label htmlFor="notes">Notes</label><textarea defaultValue={quote?.notes ?? ""} id="notes" maxLength={5000} name="notes" rows={4} /><FieldError errors={state.fieldErrors?.notes} id="notes-error" /></div><div className="field-group"><label htmlFor="terms">Terms</label><textarea defaultValue={quote?.terms ?? ""} id="terms" maxLength={5000} name="terms" rows={4} /><FieldError errors={state.fieldErrors?.terms} id="terms-error" /></div></div></section>
    {state.message ? <p className="form-message form-message-error" aria-live="polite">{state.message}</p> : null}<div className="form-actions"><Link className="button button-secondary" href={quote ? `/quotes/${quote.id}` : "/quotes"}>Cancel</Link><button className="button button-primary" disabled={pending} type="submit">{pending ? "Saving draft..." : "Save draft"}</button></div>
  </form>;
}
