import "server-only";
import { notFound } from "next/navigation";
import { requireOfficeContext } from "@/lib/customers/data";
import { createClient } from "@/lib/supabase/server";
import { JOB_PAGE_SIZE } from "./query";
import type { Job,JobActivity,JobStatus } from "./types";
import { isJobId } from "./validation";
import { jobDetailRelationships,jobListRelationships } from "./relationships";
const columns="id,organization_id,customer_id,quote_id,job_number,job_type,description,priority,status,scheduled_start_at,estimated_duration_minutes,address_line_1,address_line_2,suburb,city,postcode,completion_notes,started_at,completed_at,cancelled_at,created_at,updated_at,customers(id,first_name,last_name,email,phone),quotes(id,quote_number,status)";
export async function listJobs(p:{organizationId:string;page:number;query:string;status:JobStatus|"all"}){const s=await createClient();const from=(p.page-1)*JOB_PAGE_SIZE;let customerIds:string[]=[];if(p.query){const x=await s.from("customers").select("id").eq("organization_id",p.organizationId).or(`first_name.ilike.%${p.query}%,last_name.ilike.%${p.query}%,email.ilike.%${p.query}%`).limit(100);customerIds=(x.data??[]).map(v=>v.id)}let q=s.from("jobs").select(`${columns},${jobListRelationships}`,{count:"exact"}).eq("organization_id",p.organizationId).order("created_at",{ascending:false}).range(from,from+JOB_PAGE_SIZE-1);if(p.status!=="all")q=q.eq("status",p.status);if(p.query)q=q.or(`job_number.ilike.%${p.query}%,job_type.ilike.%${p.query}%${customerIds.length?`,customer_id.in.(${customerIds.join(",")})`:""}`);const r=await q;if(r.error)throw new Error("Unable to load jobs.");return{jobs:(r.data??[]) as unknown as Job[],count:r.count??0};}
export async function getJob(id:string,org:string){if(!isJobId(id))notFound();const s=await createClient();const r=await s.from("jobs").select(`${columns},${jobDetailRelationships}`).eq("organization_id",org).eq("id",id).order("assigned_at",{referencedTable:"job_assignments",ascending:false}).maybeSingle();if(r.error||!r.data)notFound();const data=r.data as unknown as Record<string,unknown>&{job_assignments?:Array<{organization_members:{display_name:string}}>} ;return{...data,job_assignments:data.job_assignments?.map(a=>({...a,organization_members:{...a.organization_members,profiles:{first_name:a.organization_members.display_name,last_name:""}}}))} as unknown as Job;}
export async function getJobActivity(id:string,org:string){const s=await createClient();const r=await s.from("activity_logs").select("id,summary,created_at").eq("organization_id",org).eq("entity_type","job").eq("entity_id",id).order("created_at",{ascending:false}).limit(30);if(r.error)throw new Error("Unable to load job activity.");return(r.data??[]) as JobActivity[];}
export async function getJobOptions(org:string,customerId?:string,quoteId?:string){const s=await createClient();const [customers,quotes,technicians]=await Promise.all([s.from("customers").select("id,first_name,last_name,email,address_line_1,address_line_2,suburb,city,postcode").eq("organization_id",org).eq("status","active").order("last_name").limit(100),s.from("quotes").select("id,quote_number,customer_id,notes,customers(id,first_name,last_name,email,address_line_1,address_line_2,suburb,city,postcode)").eq("organization_id",org).eq("status","accepted").order("accepted_at",{ascending:false}).limit(100),s.from("organization_members").select("id,display_name").eq("organization_id",org).eq("status","active").eq("role","technician").order("created_at")]);if(customers.error||quotes.error||technicians.error)throw new Error("Unable to load job options.");const normalizedQuotes=(quotes.data??[]).map(q=>({...q,customers:Array.isArray(q.customers)?q.customers[0]:q.customers}));const normalizedTechs=(technicians.data??[]).map(t=>({id:t.id,profiles:{first_name:t.display_name,last_name:""}}));return{customers:customers.data??[],quotes:normalizedQuotes.filter(q=>!customerId||q.customer_id===customerId||q.id===quoteId),technicians:normalizedTechs};}
export async function getRecentCustomerJobs(customerId:string,org:string){const s=await createClient();const r=await s.from("jobs").select("id,job_number,job_type,status,scheduled_start_at").eq("organization_id",org).eq("customer_id",customerId).order("created_at",{ascending:false}).limit(5);return r.error?[]:r.data??[];}
export async function getQuoteJob(quoteId:string,org:string){const s=await createClient();const r=await s.from("jobs").select("id,job_number,status").eq("organization_id",org).eq("quote_id",quoteId).maybeSingle();return r.error?null:r.data;}
export const requireJobOfficeContext=requireOfficeContext;
