import type { Metadata } from "next";
import { FileText, Plus, Search } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { QuoteList } from "@/components/quotes/quote-list";
import { listQuotes, requireQuoteOfficeContext } from "@/lib/quotes/data";
import { parseQuoteListParams, QUOTE_PAGE_SIZE, quoteListHref } from "@/lib/quotes/query";
import { quoteStatuses, quoteStatusLabels } from "@/lib/quotes/types";
export const metadata: Metadata = { title: "Quotes" };
export default async function QuotesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const params = parseQuoteListParams(await searchParams); const { organization } = await requireQuoteOfficeContext(); const { quotes, count } = await listQuotes({ organizationId: organization.id, ...params }); const pages = Math.max(1, Math.ceil(count / QUOTE_PAGE_SIZE)); if (params.page > pages && count) redirect(quoteListHref({ ...params, page: pages })); const filtered = Boolean(params.query || params.status !== "all"); return <div className="page-stack"><section className="page-heading"><div><p className="eyebrow">Financial documents</p><h1>Quotes</h1><p className="page-description">Prepare itemised proposals, issue them, and record customer outcomes.</p></div><Link className="button button-primary" href="/quotes/new"><Plus size={16} />New quote</Link></section><section className="customer-directory"><form action="/quotes" className="quote-filters" role="search"><div className="customer-search"><Search size={17} /><label className="sr-only" htmlFor="quote-search">Search quotes</label><input defaultValue={params.query} id="quote-search" name="q" placeholder="Search quote number or customer" /></div><label><span>Status</span><select defaultValue={params.status} name="status"><option value="all">All statuses</option>{quoteStatuses.map(v => <option key={v} value={v}>{quoteStatusLabels[v]}</option>)}</select></label><button className="button button-secondary">Apply</button></form><div className="directory-summary"><div><p className="eyebrow">Documents</p><h2>Quote register</h2></div>{count ? <span>{count} {count === 1 ? "quote" : "quotes"}</span> : null}</div>{quotes.length ? <QuoteList quotes={quotes} /> : <div className="customer-empty"><span className="empty-mark"><FileText size={21} /></span><h2>{filtered ? "No quotes found" : "No quotes yet"}</h2><p>{filtered ? "Try changing your search or status filter." : "Create a draft quote for an active customer to get started."}</p><Link className={`button button-${filtered ? "secondary" : "primary"}`} href={filtered ? "/quotes" : "/quotes/new"}>{filtered ? "Clear filters" : "New quote"}</Link></div>}{count > QUOTE_PAGE_SIZE ? <nav aria-label="Quote pages" className="pagination">{params.page > 1 ? <Link className="button button-secondary" href={quoteListHref({ ...params, page: params.page - 1 })}>Previous</Link> : <span />}<span>Page {params.page} of {pages}</span>{params.page < pages ? <Link className="button button-secondary" href={quoteListHref({ ...params, page: params.page + 1 })}>Next</Link> : <span />}</nav> : null}</section></div>; }
