import type { Metadata } from "next";
import { ChevronLeft, Search } from "lucide-react";
import Link from "next/link";
import { createQuoteAction } from "@/app/actions/quotes";
import { QuoteForm } from "@/components/quotes/quote-form";
import { getQuoteDefaults, getQuoteEnquiries, requireQuoteOfficeContext, searchQuoteCustomers } from "@/lib/quotes/data";
export const metadata: Metadata = { title: "New quote" };
const first = (v?: string | string[]) => (Array.isArray(v) ? v[0] : v) ?? "";
export default async function NewQuotePage({ searchParams }: { searchParams: Promise<{ customerQ?: string | string[]; customerId?: string | string[]; enquiryId?: string | string[] }> }) { const raw = await searchParams; const customerQ = first(raw.customerQ).trim().replace(/[,%()]/g, " ").slice(0, 100); const customerId = first(raw.customerId); const enquiryId = first(raw.enquiryId); const { organization } = await requireQuoteOfficeContext(); const [customers, enquiries, defaults] = await Promise.all([searchQuoteCustomers(organization.id, customerQ, customerId), getQuoteEnquiries(organization.id, customerId), getQuoteDefaults(organization.id)]); const expiry = new Date(); expiry.setUTCDate(expiry.getUTCDate() + defaults.quote_validity_days); return <div className="page-stack customer-form-page quote-form-page"><Link className="back-link" href="/quotes"><ChevronLeft size={16} />Quotes</Link><section className="page-heading"><div><p className="eyebrow">Financial documents</p><h1>New quote</h1><p className="page-description">Build a draft with server-calculated totals. You can return and issue it later.</p></div></section><form className="customer-lookup"><Search size={17} /><label className="sr-only" htmlFor="customerQ">Search active customers</label><input defaultValue={customerQ} id="customerQ" name="customerQ" placeholder="Search customer name, email or phone" /><button className="button button-secondary">Search customers</button></form>{customers.length ? <QuoteForm action={createQuoteAction} currency={defaults.currency} enquiries={enquiries} expiryDate={expiry.toISOString().slice(0, 10)} selectedCustomerId={customerId} selectedEnquiryId={enquiryId} customers={customers} taxRate={defaults.gst_registered ? Number(defaults.default_gst_rate) : 0} /> : <section className="customer-empty compact-empty"><h2>No customers available</h2><p>{customerQ ? "No active customers match this search." : "Add an active customer before creating a quote."}</p><Link className="button button-primary" href="/customers/new">Add customer</Link></section>}</div>; }
