"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireEnquiryOfficeContext } from "@/lib/enquiries/data";
import { hasEnquiryErrors, isEnquiryId, type EnquiryActionState, validateEnquiry } from "@/lib/enquiries/validation";
import { createClient } from "@/lib/supabase/server";
const fields = (d: ReturnType<typeof validateEnquiry>["data"]) => ({ p_category: d.category, p_customer_id: d.customerId, p_description: d.description, p_priority: d.priority, p_source: d.source });
export async function createEnquiryAction(_state: EnquiryActionState, form: FormData): Promise<EnquiryActionState> { const { data, fieldErrors } = validateEnquiry(form); if (hasEnquiryErrors(fieldErrors)) return { fieldErrors, status: "error" }; const { organization } = await requireEnquiryOfficeContext(); const s = await createClient(); const r = await s.rpc("create_enquiry", { p_organization_id: organization.id, ...fields(data) }); if (r.error || typeof r.data !== "string") return { message: "KiwiOps could not create this enquiry. Confirm the customer is active and try again.", status: "error" }; revalidatePath("/enquiries"); revalidatePath(`/customers/${data.customerId}`); redirect(`/enquiries/${r.data}?notice=created`); }
export async function updateEnquiryAction(id: string, customerId: string, _state: EnquiryActionState, form: FormData): Promise<EnquiryActionState> { if (!isEnquiryId(id) || !isEnquiryId(customerId)) return { message: "This enquiry could not be found.", status: "error" }; form.set("customerId", customerId); const { data, fieldErrors } = validateEnquiry(form, true); if (hasEnquiryErrors(fieldErrors)) return { fieldErrors, status: "error" }; await requireEnquiryOfficeContext(); const s = await createClient(); const r = await s.rpc("update_enquiry", { p_enquiry_id: id, p_status: data.status, ...fields(data) }); if (r.error) return { message: "KiwiOps could not update this enquiry. Check your access and try again.", status: "error" }; revalidatePath("/enquiries"); revalidatePath(`/enquiries/${id}`); revalidatePath(`/customers/${customerId}`); redirect(`/enquiries/${id}?notice=updated`); }
