"use server";
/* eslint-disable @typescript-eslint/no-unused-vars */
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { requireJobOfficeContext } from "@/lib/jobs/data";import { hasJobErrors,isJobId,type JobActionState,validateJob } from "@/lib/jobs/validation";import { createClient } from "@/lib/supabase/server";
const fields=(d:ReturnType<typeof validateJob>["data"])=>({p_customer_id:d.customerId,p_quote_id:d.quoteId,p_job_type:d.jobType,p_description:d.description,p_priority:d.priority,p_scheduled_start_local:d.scheduledStart,p_estimated_duration_minutes:d.duration,p_address_line_1:d.address1,p_address_line_2:d.address2,p_suburb:d.suburb,p_city:d.city,p_postcode:d.postcode,p_assignee_member_ids:d.assignees});
export async function createJobAction(_:JobActionState,f:FormData):Promise<JobActionState>{const{data,fieldErrors}=validateJob(f);if(hasJobErrors(fieldErrors))return{fieldErrors,status:"error"};const{organization}=await requireJobOfficeContext();const s=await createClient();const r=await s.rpc("create_job",{p_organization_id:organization.id,...fields(data)});if(r.error||typeof r.data!=="string")return{message:r.error?.message.includes("already has")?"This accepted quote already has a job.":"KiwiOps could not create this job. Check the customer, quote, address, and technicians.",status:"error"};revalidatePath("/jobs");revalidatePath(`/customers/${data.customerId}`);if(data.quoteId)revalidatePath(`/quotes/${data.quoteId}`);redirect(`/jobs/${r.data}?notice=created`);}
export async function updateJobAction(id:string,updated:string,_:JobActionState,f:FormData):Promise<JobActionState>{if(!isJobId(id))return{message:"Job not found.",status:"error"};const{data,fieldErrors}=validateJob(f);if(hasJobErrors(fieldErrors))return{fieldErrors,status:"error"};await requireJobOfficeContext();const s=await createClient();const r=await s.rpc("update_job",{p_job_id:id,p_expected_updated_at:updated,...Object.fromEntries(Object.entries(fields(data)).filter(([k])=>!['p_customer_id','p_quote_id'].includes(k)))});if(r.error)return{message:r.error.message.includes("another user")?"This job changed in another session. Refresh before saving.":"KiwiOps could not update this job. Check its status and details.",status:"error"};revalidatePath("/jobs");revalidatePath(`/jobs/${id}`);redirect(`/jobs/${id}?notice=updated`);}
export async function startJobAction(id:string,_:JobActionState){if(!isJobId(id))return{message:"Job not found.",status:"error"} as JobActionState;await requireJobOfficeContext();const s=await createClient();const r=await s.rpc("start_job",{p_job_id:id});if(r.error)return{message:"Only a scheduled job can be started.",status:"error"} as JobActionState;revalidatePath("/jobs");redirect(`/jobs/${id}?notice=started`);}
export async function completeJobAction(id:string,_:JobActionState,f:FormData){if(!isJobId(id))return{message:"Job not found.",status:"error"} as JobActionState;await requireJobOfficeContext();const s=await createClient();const r=await s.rpc("complete_job",{p_job_id:id,p_completion_notes:String(f.get("completionNotes")??"").trim()||null});if(r.error)return{message:"Only an in-progress job can be completed.",status:"error"} as JobActionState;revalidatePath("/jobs");redirect(`/jobs/${id}?notice=completed`);}
export async function cancelJobAction(id:string,_:JobActionState){if(!isJobId(id))return{message:"Job not found.",status:"error"} as JobActionState;await requireJobOfficeContext();const s=await createClient();const r=await s.rpc("cancel_job",{p_job_id:id});if(r.error)return{message:"This job cannot be cancelled.",status:"error"} as JobActionState;revalidatePath("/jobs");redirect(`/jobs/${id}?notice=cancelled`);}
