"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireQuoteOfficeContext } from "@/lib/quotes/data";
import { hasQuoteErrors, isQuoteId, type QuoteActionState, validateQuote } from "@/lib/quotes/validation";
import { createClient } from "@/lib/supabase/server";
const rpcFields = (d: ReturnType<typeof validateQuote>["data"]) => ({ p_customer_id: d.customerId, p_enquiry_id: d.enquiryId, p_expiry_date: d.expiryDate, p_notes: d.notes, p_terms: d.terms, p_items: d.items });
export async function createQuoteAction(state: QuoteActionState, form: FormData): Promise<QuoteActionState> { void state; const { data, fieldErrors } = validateQuote(form); if (hasQuoteErrors(fieldErrors)) return { fieldErrors, status: "error" }; const { organization } = await requireQuoteOfficeContext(); const s = await createClient(); const r = await s.rpc("create_quote", { p_organization_id: organization.id, ...rpcFields(data) }); if (r.error || typeof r.data !== "string") return { message: "KiwiOps could not create this quote. Check the customer, enquiry, expiry date, and line items.", status: "error" }; revalidatePath("/quotes"); revalidatePath(`/customers/${data.customerId}`); if (data.enquiryId) revalidatePath(`/enquiries/${data.enquiryId}`); redirect(`/quotes/${r.data}?notice=created`); }
export async function updateQuoteAction(id: string, expectedUpdatedAt: string, state: QuoteActionState, form: FormData): Promise<QuoteActionState> { void state; if (!isQuoteId(id)) return { message: "This quote could not be found.", status: "error" }; const { data, fieldErrors } = validateQuote(form); if (hasQuoteErrors(fieldErrors)) return { fieldErrors, status: "error" }; await requireQuoteOfficeContext(); const s = await createClient(); const r = await s.rpc("update_draft_quote", { p_quote_id: id, p_expected_updated_at: expectedUpdatedAt, ...rpcFields(data) }); if (r.error) return { message: r.error.message.includes("another user") ? "This draft changed in another session. Refresh before saving again." : "KiwiOps could not save this draft. Check its status and line items.", status: "error" }; revalidatePath("/quotes"); revalidatePath(`/quotes/${id}`); redirect(`/quotes/${id}?notice=updated`); }
export async function issueQuoteAction(id: string, state: QuoteActionState): Promise<QuoteActionState> { void state; if (!isQuoteId(id)) return { message: "This quote could not be found.", status: "error" }; await requireQuoteOfficeContext(); const s = await createClient(); const r = await s.rpc("issue_quote", { p_quote_id: id }); if (r.error) return { message: "This quote could not be issued. It may have no line items or may no longer be a draft.", status: "error" }; revalidatePath("/quotes"); revalidatePath(`/quotes/${id}`); revalidatePath("/enquiries"); redirect(`/quotes/${id}?notice=issued`); }
export async function quoteOutcomeAction(id: string, outcome: "accepted" | "rejected", state: QuoteActionState): Promise<QuoteActionState> { void state; if (!isQuoteId(id)) return { message: "This quote could not be found.", status: "error" }; await requireQuoteOfficeContext(); const s = await createClient(); const r = await s.rpc("set_quote_outcome", { p_quote_id: id, p_status: outcome }); if (r.error) return { message: "This quote outcome could not be recorded. Only issued quotes can be updated.", status: "error" }; revalidatePath("/quotes"); revalidatePath(`/quotes/${id}`); redirect(`/quotes/${id}?notice=${outcome}`); }
